language: cpp

compiler:
    - gcc

git:
  depth: 1

install:
    - sudo pip install cpp-coveralls
    - sudo apt-get update -qq
    - sudo apt-get install -qq cmake python3-minimal
    - sudo apt-get install -qq valgrind

script:
    - ./clean.py --rebuild
    - cd build
    - cmake ..
    - make

after_success:
    #- coveralls


